use crate::models::*;
use std::collections::HashMap;

pub fn system_default_platforms() -> Vec<PlatformConfig> {
    vec![
        PlatformConfig {
            name: "Google Search".into(),
            enabled: true,
            priority: 10,
            platform_type: PlatformType::SearchEngine,
            base_urls: vec!["https://www.google.com/search".into()],
            query_templates: default_query_templates("Google Search"),
            rate_limit_rps: 2.0,
            timeout_ms: 15000,
            max_pages: 3,
            max_results: 30,
            max_concurrency: 4,
            retry_count: 2,
            backoff_strategy: "exponential".into(),
            default_region: "global".into(),
            default_language: "en".into(),
            participate_quick: true,
            participate_deep: true,
            parse_fields: ParseFields::default(),
            signal_weights: SignalWeights { demand_signal: 1.0, dissatisfaction_signal: 0.7, review_credibility: 0.8, freshness: 1.2 },
        },
        PlatformConfig {
            name: "Reddit".into(),
            enabled: true,
            priority: 9,
            platform_type: PlatformType::SocialForum,
            base_urls: vec!["https://www.reddit.com".into()],
            query_templates: default_query_templates("Reddit"),
            rate_limit_rps: 1.5,
            timeout_ms: 12000,
            max_pages: 2,
            max_results: 25,
            max_concurrency: 3,
            retry_count: 3,
            backoff_strategy: "exponential".into(),
            default_region: "global".into(),
            default_language: "en".into(),
            participate_quick: true,
            participate_deep: true,
            parse_fields: ParseFields::default(),
            signal_weights: SignalWeights { demand_signal: 1.2, dissatisfaction_signal: 1.5, review_credibility: 0.9, freshness: 1.0 },
        },
        PlatformConfig {
            name: "G2 / Capterra".into(),
            enabled: true,
            priority: 8,
            platform_type: PlatformType::ReviewSite,
            base_urls: vec!["https://www.g2.com".into(), "https://www.capterra.com".into()],
            query_templates: default_query_templates("G2 / Capterra"),
            rate_limit_rps: 1.0,
            timeout_ms: 15000,
            max_pages: 3,
            max_results: 20,
            max_concurrency: 2,
            retry_count: 2,
            backoff_strategy: "exponential".into(),
            default_region: "us".into(),
            default_language: "en".into(),
            participate_quick: true,
            participate_deep: true,
            parse_fields: ParseFields::default(),
            signal_weights: SignalWeights { demand_signal: 0.8, dissatisfaction_signal: 1.5, review_credibility: 1.2, freshness: 0.8 },
        },
        PlatformConfig {
            name: "App Store".into(),
            enabled: true,
            priority: 7,
            platform_type: PlatformType::AppStore,
            base_urls: vec!["https://apps.apple.com".into(), "https://play.google.com".into()],
            query_templates: default_query_templates("App Store"),
            rate_limit_rps: 2.0,
            timeout_ms: 10000,
            max_pages: 2,
            max_results: 50,
            max_concurrency: 3,
            retry_count: 2,
            backoff_strategy: "exponential".into(),
            default_region: "us".into(),
            default_language: "en".into(),
            participate_quick: true,
            participate_deep: true,
            parse_fields: ParseFields::default(),
            signal_weights: SignalWeights { demand_signal: 0.9, dissatisfaction_signal: 1.3, review_credibility: 1.0, freshness: 1.0 },
        },
        PlatformConfig {
            name: "Product Hunt".into(),
            enabled: false,
            priority: 5,
            platform_type: PlatformType::ProductDirectory,
            base_urls: vec!["https://www.producthunt.com".into()],
            query_templates: default_query_templates("Product Hunt"),
            rate_limit_rps: 1.0,
            timeout_ms: 10000,
            max_pages: 2,
            max_results: 20,
            max_concurrency: 2,
            retry_count: 2,
            backoff_strategy: "exponential".into(),
            default_region: "global".into(),
            default_language: "en".into(),
            participate_quick: false,
            participate_deep: true,
            parse_fields: ParseFields::default(),
            signal_weights: SignalWeights { demand_signal: 0.7, dissatisfaction_signal: 0.8, review_credibility: 0.7, freshness: 1.1 },
        },
        PlatformConfig {
            name: "X / Twitter".into(),
            enabled: false,
            priority: 4,
            platform_type: PlatformType::SocialMedia,
            base_urls: vec!["https://x.com".into()],
            query_templates: default_query_templates("X / Twitter"),
            rate_limit_rps: 1.0,
            timeout_ms: 10000,
            max_pages: 1,
            max_results: 20,
            max_concurrency: 1,
            retry_count: 2,
            backoff_strategy: "exponential".into(),
            default_region: "global".into(),
            default_language: "en".into(),
            participate_quick: false,
            participate_deep: true,
            parse_fields: ParseFields::default(),
            signal_weights: SignalWeights { demand_signal: 0.6, dissatisfaction_signal: 0.9, review_credibility: 0.6, freshness: 1.3 },
        },
        PlatformConfig {
            name: "AlternativeTo".into(),
            enabled: false,
            priority: 5,
            platform_type: PlatformType::ProductDirectory,
            base_urls: vec!["https://alternativeto.net".into()],
            query_templates: default_query_templates("AlternativeTo"),
            rate_limit_rps: 1.0,
            timeout_ms: 10000,
            max_pages: 2,
            max_results: 30,
            max_concurrency: 2,
            retry_count: 2,
            backoff_strategy: "exponential".into(),
            default_region: "global".into(),
            default_language: "en".into(),
            participate_quick: false,
            participate_deep: true,
            parse_fields: ParseFields::default(),
            signal_weights: SignalWeights { demand_signal: 0.6, dissatisfaction_signal: 0.7, review_credibility: 0.6, freshness: 0.8 },
        },
        PlatformConfig {
            name: "YouTube".into(),
            enabled: false,
            priority: 4,
            platform_type: PlatformType::SocialMedia,
            base_urls: vec!["https://www.youtube.com".into()],
            query_templates: vec![
                QueryTemplate {
                    name: "Product Review".into(),
                    template: "{core_keyword} review 2026".into(),
                    enabled: true,
                    query_type: QueryType::Brand,
                    applicable_product_types: vec![],
                },
                QueryTemplate {
                    name: "Comparison Video".into(),
                    template: "{core_keyword} vs alternative".into(),
                    enabled: true,
                    query_type: QueryType::Compare,
                    applicable_product_types: vec![],
                },
                QueryTemplate {
                    name: "Tutorial/Demo".into(),
                    template: "how to use {core_keyword}".into(),
                    enabled: true,
                    query_type: QueryType::Task,
                    applicable_product_types: vec![],
                },
            ],
            rate_limit_rps: 1.0,
            timeout_ms: 15000,
            max_pages: 1,
            max_results: 10,
            max_concurrency: 1,
            retry_count: 2,
            backoff_strategy: "exponential".into(),
            default_region: "global".into(),
            default_language: "en".into(),
            participate_quick: false,
            participate_deep: true,
            parse_fields: ParseFields::default(),
            signal_weights: SignalWeights { demand_signal: 0.6, dissatisfaction_signal: 0.7, review_credibility: 0.7, freshness: 1.1 },
        },
        PlatformConfig {
            name: "LinkedIn".into(),
            enabled: false,
            priority: 4,
            platform_type: PlatformType::SocialMedia,
            base_urls: vec!["https://www.linkedin.com".into()],
            query_templates: vec![
                QueryTemplate {
                    name: "Industry Discussion".into(),
                    template: "{core_keyword} industry trend 2026".into(),
                    enabled: true,
                    query_type: QueryType::Category,
                    applicable_product_types: vec![],
                },
                QueryTemplate {
                    name: "Product Posts".into(),
                    template: "{core_keyword} tool product".into(),
                    enabled: true,
                    query_type: QueryType::Brand,
                    applicable_product_types: vec![],
                },
            ],
            rate_limit_rps: 1.0,
            timeout_ms: 15000,
            max_pages: 1,
            max_results: 10,
            max_concurrency: 1,
            retry_count: 2,
            backoff_strategy: "exponential".into(),
            default_region: "global".into(),
            default_language: "en".into(),
            participate_quick: false,
            participate_deep: true,
            parse_fields: ParseFields::default(),
            signal_weights: SignalWeights { demand_signal: 0.5, dissatisfaction_signal: 0.6, review_credibility: 0.6, freshness: 1.0 },
        },
        PlatformConfig {
            name: "Zhihu".into(),
            enabled: false,
            priority: 4,
            platform_type: PlatformType::SocialForum,
            base_urls: vec!["https://www.zhihu.com".into()],
            query_templates: vec![
                QueryTemplate {
                    name: "Product Discussion".into(),
                    template: "{core_keyword} 好用吗 推荐".into(),
                    enabled: true,
                    query_type: QueryType::Category,
                    applicable_product_types: vec![],
                },
                QueryTemplate {
                    name: "Alternative Search".into(),
                    template: "{core_keyword} 替代 对比".into(),
                    enabled: true,
                    query_type: QueryType::Compare,
                    applicable_product_types: vec![],
                },
                QueryTemplate {
                    name: "Pain Point Search".into(),
                    template: "{core_keyword} 缺点 吐槽".into(),
                    enabled: true,
                    query_type: QueryType::Problem,
                    applicable_product_types: vec![],
                },
            ],
            rate_limit_rps: 1.0,
            timeout_ms: 15000,
            max_pages: 2,
            max_results: 15,
            max_concurrency: 1,
            retry_count: 2,
            backoff_strategy: "exponential".into(),
            default_region: "cn".into(),
            default_language: "zh".into(),
            participate_quick: false,
            participate_deep: true,
            parse_fields: ParseFields::default(),
            signal_weights: SignalWeights { demand_signal: 0.7, dissatisfaction_signal: 0.9, review_credibility: 0.8, freshness: 1.0 },
        },
        PlatformConfig {
            name: "Amazon".into(),
            enabled: false, priority: 3,
            platform_type: PlatformType::ECommerce,
            base_urls: vec!["https://www.amazon.com".into()],
            query_templates: default_query_templates("Amazon"),
            rate_limit_rps: 1.0, timeout_ms: 15000, max_pages: 1, max_results: 20,
            max_concurrency: 1, retry_count: 2, backoff_strategy: "exponential".into(),
            default_region: "us".into(), default_language: "en".into(),
            participate_quick: false, participate_deep: false,
            parse_fields: ParseFields::default(),
            signal_weights: SignalWeights { demand_signal: 0.5, dissatisfaction_signal: 0.8, review_credibility: 0.7, freshness: 0.5 },
        },
        PlatformConfig {
            name: "Etsy".into(),
            enabled: false, priority: 2,
            platform_type: PlatformType::ECommerce,
            base_urls: vec!["https://www.etsy.com".into()],
            query_templates: default_query_templates("Etsy"),
            rate_limit_rps: 1.0, timeout_ms: 15000, max_pages: 1, max_results: 20,
            max_concurrency: 1, retry_count: 2, backoff_strategy: "exponential".into(),
            default_region: "us".into(), default_language: "en".into(),
            participate_quick: false, participate_deep: false,
            parse_fields: ParseFields::default(),
            signal_weights: SignalWeights { demand_signal: 0.4, dissatisfaction_signal: 0.7, review_credibility: 0.6, freshness: 0.5 },
        },
        PlatformConfig {
            name: "Taobao".into(),
            enabled: false, priority: 2,
            platform_type: PlatformType::ECommerce,
            base_urls: vec!["https://www.taobao.com".into()],
            query_templates: default_query_templates("Taobao"),
            rate_limit_rps: 1.0, timeout_ms: 15000, max_pages: 1, max_results: 20,
            max_concurrency: 1, retry_count: 2, backoff_strategy: "exponential".into(),
            default_region: "cn".into(), default_language: "zh".into(),
            participate_quick: false, participate_deep: false,
            parse_fields: ParseFields::default(),
            signal_weights: SignalWeights { demand_signal: 0.4, dissatisfaction_signal: 0.7, review_credibility: 0.6, freshness: 0.5 },
        },
        // ── New platforms from PRD ──
        PlatformConfig {
            name: "Bing".into(),
            enabled: true, priority: 8,
            platform_type: PlatformType::SearchEngine,
            base_urls: vec!["https://www.bing.com".into()],
            query_templates: default_query_templates("Bing"),
            rate_limit_rps: 2.0, timeout_ms: 15000, max_pages: 3, max_results: 30,
            max_concurrency: 4, retry_count: 2, backoff_strategy: "exponential".into(),
            default_region: "global".into(), default_language: "en".into(),
            participate_quick: true, participate_deep: true,
            parse_fields: ParseFields::default(),
            signal_weights: SignalWeights { demand_signal: 0.9, dissatisfaction_signal: 0.6, review_credibility: 0.7, freshness: 1.1 },
        },
        PlatformConfig {
            name: "Google Play".into(),
            enabled: true, priority: 7,
            platform_type: PlatformType::AppStore,
            base_urls: vec!["https://play.google.com".into()],
            query_templates: default_query_templates("Google Play"),
            rate_limit_rps: 2.0, timeout_ms: 10000, max_pages: 2, max_results: 50,
            max_concurrency: 3, retry_count: 2, backoff_strategy: "exponential".into(),
            default_region: "us".into(), default_language: "en".into(),
            participate_quick: true, participate_deep: true,
            parse_fields: ParseFields::default(),
            signal_weights: SignalWeights { demand_signal: 0.9, dissatisfaction_signal: 1.2, review_credibility: 1.0, freshness: 1.0 },
        },
        PlatformConfig {
            name: "Chrome Web Store".into(),
            enabled: false, priority: 3,
            platform_type: PlatformType::AppStore,
            base_urls: vec!["https://chromewebstore.google.com".into()],
            query_templates: default_query_templates("Chrome Web Store"),
            rate_limit_rps: 1.5, timeout_ms: 12000, max_pages: 2, max_results: 30,
            max_concurrency: 2, retry_count: 2, backoff_strategy: "exponential".into(),
            default_region: "global".into(), default_language: "en".into(),
            participate_quick: false, participate_deep: true,
            parse_fields: ParseFields::default(),
            signal_weights: SignalWeights { demand_signal: 0.5, dissatisfaction_signal: 0.8, review_credibility: 0.7, freshness: 0.8 },
        },
        PlatformConfig {
            name: "Quora".into(),
            enabled: true, priority: 6,
            platform_type: PlatformType::SocialForum,
            base_urls: vec!["https://www.quora.com".into()],
            query_templates: default_query_templates("Quora"),
            rate_limit_rps: 1.5, timeout_ms: 12000, max_pages: 2, max_results: 25,
            max_concurrency: 3, retry_count: 2, backoff_strategy: "exponential".into(),
            default_region: "global".into(), default_language: "en".into(),
            participate_quick: true, participate_deep: true,
            parse_fields: ParseFields::default(),
            signal_weights: SignalWeights { demand_signal: 1.0, dissatisfaction_signal: 1.1, review_credibility: 0.8, freshness: 0.9 },
        },
        PlatformConfig {
            name: "TikTok".into(),
            enabled: false, priority: 4,
            platform_type: PlatformType::SocialMedia,
            base_urls: vec!["https://www.tiktok.com".into()],
            query_templates: default_query_templates("TikTok"),
            rate_limit_rps: 1.0, timeout_ms: 10000, max_pages: 1, max_results: 20,
            max_concurrency: 1, retry_count: 2, backoff_strategy: "exponential".into(),
            default_region: "global".into(), default_language: "en".into(),
            participate_quick: false, participate_deep: true,
            parse_fields: ParseFields::default(),
            signal_weights: SignalWeights { demand_signal: 0.5, dissatisfaction_signal: 0.7, review_credibility: 0.5, freshness: 1.3 },
        },
        PlatformConfig {
            name: "Trustpilot".into(),
            enabled: true, priority: 7,
            platform_type: PlatformType::ReviewSite,
            base_urls: vec!["https://www.trustpilot.com".into()],
            query_templates: default_query_templates("Trustpilot"),
            rate_limit_rps: 1.0, timeout_ms: 15000, max_pages: 3, max_results: 25,
            max_concurrency: 2, retry_count: 2, backoff_strategy: "exponential".into(),
            default_region: "global".into(), default_language: "en".into(),
            participate_quick: true, participate_deep: true,
            parse_fields: ParseFields::default(),
            signal_weights: SignalWeights { demand_signal: 0.7, dissatisfaction_signal: 1.4, review_credibility: 1.1, freshness: 0.8 },
        },
        PlatformConfig {
            name: "Google Trends".into(),
            enabled: false, priority: 5,
            platform_type: PlatformType::SearchEngine,
            base_urls: vec!["https://trends.google.com".into()],
            query_templates: vec![
                QueryTemplate {
                    name: "Trend Explore".into(),
                    template: "{core_keyword}".into(),
                    enabled: true,
                    query_type: QueryType::Category,
                    applicable_product_types: vec![],
                },
                QueryTemplate {
                    name: "Compare Trends".into(),
                    template: "{core_keyword},{competitor_name}".into(),
                    enabled: true,
                    query_type: QueryType::Compare,
                    applicable_product_types: vec![],
                },
            ],
            rate_limit_rps: 0.5, timeout_ms: 15000, max_pages: 1, max_results: 5,
            max_concurrency: 1, retry_count: 2, backoff_strategy: "exponential".into(),
            default_region: "global".into(), default_language: "en".into(),
            participate_quick: false, participate_deep: true,
            parse_fields: ParseFields { title: true, summary: true, comments: false, rating: false, date: true, author: false, raw_html: true },
            signal_weights: SignalWeights { demand_signal: 0.8, dissatisfaction_signal: 0.0, review_credibility: 0.4, freshness: 1.5 },
        },
        PlatformConfig {
            name: "Tieba".into(),
            enabled: false, priority: 5,
            platform_type: PlatformType::SocialForum,
            base_urls: vec!["https://tieba.baidu.com".into()],
            query_templates: vec![
                QueryTemplate {
                    name: "吧内搜索".into(),
                    template: "{core_keyword} 怎么样 推荐".into(),
                    enabled: true,
                    query_type: QueryType::Category,
                    applicable_product_types: vec![],
                },
                QueryTemplate {
                    name: "对比讨论".into(),
                    template: "{core_keyword} 对比 {competitor_name}".into(),
                    enabled: true,
                    query_type: QueryType::Compare,
                    applicable_product_types: vec![],
                },
                QueryTemplate {
                    name: "吐槽搜索".into(),
                    template: "{core_keyword} 坑 不好用 后悔".into(),
                    enabled: true,
                    query_type: QueryType::Problem,
                    applicable_product_types: vec![],
                },
            ],
            rate_limit_rps: 1.0, timeout_ms: 15000, max_pages: 2, max_results: 20,
            max_concurrency: 2, retry_count: 2, backoff_strategy: "exponential".into(),
            default_region: "cn".into(), default_language: "zh".into(),
            participate_quick: false, participate_deep: true,
            parse_fields: ParseFields::default(),
            signal_weights: SignalWeights { demand_signal: 0.7, dissatisfaction_signal: 1.0, review_credibility: 0.7, freshness: 0.8 },
        },
        PlatformConfig {
            name: "Douban".into(),
            enabled: false, priority: 5,
            platform_type: PlatformType::ReviewSite,
            base_urls: vec!["https://www.douban.com".into()],
            query_templates: vec![
                QueryTemplate {
                    name: "产品搜索".into(),
                    template: "{core_keyword} 评价 推荐".into(),
                    enabled: true,
                    query_type: QueryType::Category,
                    applicable_product_types: vec![],
                },
                QueryTemplate {
                    name: "吐槽搜索".into(),
                    template: "{core_keyword} 吐槽 差评 失望".into(),
                    enabled: true,
                    query_type: QueryType::Problem,
                    applicable_product_types: vec![],
                },
                QueryTemplate {
                    name: "对比搜索".into(),
                    template: "{core_keyword} vs {competitor_name} 哪个好".into(),
                    enabled: true,
                    query_type: QueryType::Compare,
                    applicable_product_types: vec![],
                },
            ],
            rate_limit_rps: 1.0, timeout_ms: 15000, max_pages: 2, max_results: 20,
            max_concurrency: 2, retry_count: 2, backoff_strategy: "exponential".into(),
            default_region: "cn".into(), default_language: "zh".into(),
            participate_quick: false, participate_deep: true,
            parse_fields: ParseFields::default(),
            signal_weights: SignalWeights { demand_signal: 0.6, dissatisfaction_signal: 0.9, review_credibility: 0.7, freshness: 0.8 },
        },
        PlatformConfig {
            name: "JD.com".into(),
            enabled: false, priority: 3,
            platform_type: PlatformType::ECommerce,
            base_urls: vec!["https://www.jd.com".into()],
            query_templates: vec![
                QueryTemplate {
                    name: "商品搜索".into(),
                    template: "{core_keyword} 评价 销量".into(),
                    enabled: true,
                    query_type: QueryType::Category,
                    applicable_product_types: vec![],
                },
                QueryTemplate {
                    name: "差评搜索".into(),
                    template: "{core_keyword} 差评 质量 售后".into(),
                    enabled: true,
                    query_type: QueryType::Problem,
                    applicable_product_types: vec![],
                },
            ],
            rate_limit_rps: 1.0, timeout_ms: 15000, max_pages: 1, max_results: 20,
            max_concurrency: 1, retry_count: 2, backoff_strategy: "exponential".into(),
            default_region: "cn".into(), default_language: "zh".into(),
            participate_quick: false, participate_deep: false,
            parse_fields: ParseFields::default(),
            signal_weights: SignalWeights { demand_signal: 0.4, dissatisfaction_signal: 0.8, review_credibility: 0.7, freshness: 0.5 },
        },
    ]
}

fn default_query_templates(platform: &str) -> Vec<QueryTemplate> {
    match platform {
        "Google Search" => vec![
            QueryTemplate {
                name: "Category Query".into(),
                template: "{core_keyword} tools alternatives comparison".into(),
                enabled: true,
                query_type: QueryType::Category,
                applicable_product_types: vec![],
            },
            QueryTemplate {
                name: "Problem Query".into(),
                template: "{problem} solution software {year}".into(),
                enabled: true,
                query_type: QueryType::Problem,
                applicable_product_types: vec![],
            },
            QueryTemplate {
                name: "Competitor Compare".into(),
                template: "{competitor_name} vs alternative".into(),
                enabled: true,
                query_type: QueryType::Compare,
                applicable_product_types: vec![],
            },
            QueryTemplate {
                name: "Pricing Query".into(),
                template: "{competitor_name} pricing plans cost".into(),
                enabled: false,
                query_type: QueryType::Pricing,
                applicable_product_types: vec![],
            },
        ],
        "Reddit" => vec![
            QueryTemplate {
                name: "Pain Point Dig".into(),
                template: "r/{subreddit} {problem} frustrated".into(),
                enabled: true,
                query_type: QueryType::Task,
                applicable_product_types: vec![],
            },
            QueryTemplate {
                name: "Alternative Search".into(),
                template: "alternative to {competitor_name} reddit".into(),
                enabled: true,
                query_type: QueryType::Compare,
                applicable_product_types: vec![],
            },
            QueryTemplate {
                name: "Recommendation".into(),
                template: "r/{subreddit} best {category} tool for".into(),
                enabled: true,
                query_type: QueryType::Category,
                applicable_product_types: vec![],
            },
        ],
        "G2 / Capterra" => vec![
            QueryTemplate {
                name: "Review Mining".into(),
                template: "{core_keyword} review complaints {year}".into(),
                enabled: true,
                query_type: QueryType::Problem,
                applicable_product_types: vec![],
            },
            QueryTemplate {
                name: "Competitor Scrape".into(),
                template: "{competitor_name} reviews pros cons".into(),
                enabled: true,
                query_type: QueryType::Brand,
                applicable_product_types: vec![],
            },
        ],
        "App Store" => vec![
            QueryTemplate {
                name: "App Search".into(),
                template: "{core_keyword}".into(),
                enabled: true,
                query_type: QueryType::Category,
                applicable_product_types: vec![],
            },
            QueryTemplate {
                name: "Alternative App".into(),
                template: "{competitor_name}".into(),
                enabled: true,
                query_type: QueryType::Brand,
                applicable_product_types: vec![],
            },
        ],
        "Bing" => vec![
            QueryTemplate {
                name: "Category Query".into(),
                template: "{core_keyword} tools alternatives comparison".into(),
                enabled: true,
                query_type: QueryType::Category,
                applicable_product_types: vec![],
            },
            QueryTemplate {
                name: "Problem Query".into(),
                template: "{problem} solution software {year}".into(),
                enabled: true,
                query_type: QueryType::Problem,
                applicable_product_types: vec![],
            },
            QueryTemplate {
                name: "Competitor Compare".into(),
                template: "{competitor_name} vs alternative".into(),
                enabled: true,
                query_type: QueryType::Compare,
                applicable_product_types: vec![],
            },
        ],
        "Google Play" => vec![
            QueryTemplate {
                name: "App Search".into(),
                template: "{core_keyword}".into(),
                enabled: true,
                query_type: QueryType::Category,
                applicable_product_types: vec![],
            },
            QueryTemplate {
                name: "Competitor App".into(),
                template: "{competitor_name}".into(),
                enabled: true,
                query_type: QueryType::Brand,
                applicable_product_types: vec![],
            },
            QueryTemplate {
                name: "Review Mining".into(),
                template: "{core_keyword} review complaints".into(),
                enabled: true,
                query_type: QueryType::Problem,
                applicable_product_types: vec![],
            },
        ],
        "Chrome Web Store" => vec![
            QueryTemplate {
                name: "Extension Search".into(),
                template: "{core_keyword} extension".into(),
                enabled: true,
                query_type: QueryType::Category,
                applicable_product_types: vec![],
            },
            QueryTemplate {
                name: "Competitor Extension".into(),
                template: "{competitor_name} extension".into(),
                enabled: true,
                query_type: QueryType::Brand,
                applicable_product_types: vec![],
            },
            QueryTemplate {
                name: "Alternative Extension".into(),
                template: "alternative to {core_keyword} extension".into(),
                enabled: true,
                query_type: QueryType::Compare,
                applicable_product_types: vec![],
            },
        ],
        "Quora" => vec![
            QueryTemplate {
                name: "Problem Discovery".into(),
                template: "what is the best {category} tool for".into(),
                enabled: true,
                query_type: QueryType::Category,
                applicable_product_types: vec![],
            },
            QueryTemplate {
                name: "Alternative Discussion".into(),
                template: "alternative to {competitor_name} for".into(),
                enabled: true,
                query_type: QueryType::Compare,
                applicable_product_types: vec![],
            },
            QueryTemplate {
                name: "Experience Sharing".into(),
                template: "{core_keyword} experience review pros cons".into(),
                enabled: true,
                query_type: QueryType::Brand,
                applicable_product_types: vec![],
            },
        ],
        "TikTok" => vec![
            QueryTemplate {
                name: "Trend Discovery".into(),
                template: "{core_keyword} review 2026".into(),
                enabled: true,
                query_type: QueryType::Brand,
                applicable_product_types: vec![],
            },
            QueryTemplate {
                name: "Comparison".into(),
                template: "{core_keyword} vs alternative".into(),
                enabled: true,
                query_type: QueryType::Compare,
                applicable_product_types: vec![],
            },
        ],
        "Trustpilot" => vec![
            QueryTemplate {
                name: "Company Review".into(),
                template: "{core_keyword} review complaints trustpilot".into(),
                enabled: true,
                query_type: QueryType::Problem,
                applicable_product_types: vec![],
            },
            QueryTemplate {
                name: "Competitor Review".into(),
                template: "{competitor_name} reviews trustpilot pros cons".into(),
                enabled: true,
                query_type: QueryType::Brand,
                applicable_product_types: vec![],
            },
            QueryTemplate {
                name: "Category Comparison".into(),
                template: "best {category} 2026 trustpilot".into(),
                enabled: true,
                query_type: QueryType::Category,
                applicable_product_types: vec![],
            },
        ],
        "Tieba" => vec![
            QueryTemplate {
                name: "吧内搜索".into(),
                template: "{core_keyword} 怎么样 推荐".into(),
                enabled: true,
                query_type: QueryType::Category,
                applicable_product_types: vec![],
            },
            QueryTemplate {
                name: "对比讨论".into(),
                template: "{core_keyword} 对比 {competitor_name}".into(),
                enabled: true,
                query_type: QueryType::Compare,
                applicable_product_types: vec![],
            },
            QueryTemplate {
                name: "吐槽搜索".into(),
                template: "{core_keyword} 坑 不好用 后悔".into(),
                enabled: true,
                query_type: QueryType::Problem,
                applicable_product_types: vec![],
            },
        ],
        "Douban" => vec![
            QueryTemplate {
                name: "产品搜索".into(),
                template: "{core_keyword} 评价 推荐".into(),
                enabled: true,
                query_type: QueryType::Category,
                applicable_product_types: vec![],
            },
            QueryTemplate {
                name: "吐槽搜索".into(),
                template: "{core_keyword} 吐槽 差评 失望".into(),
                enabled: true,
                query_type: QueryType::Problem,
                applicable_product_types: vec![],
            },
            QueryTemplate {
                name: "对比搜索".into(),
                template: "{core_keyword} vs {competitor_name} 哪个好".into(),
                enabled: true,
                query_type: QueryType::Compare,
                applicable_product_types: vec![],
            },
        ],
        "JD.com" => vec![
            QueryTemplate {
                name: "商品搜索".into(),
                template: "{core_keyword} 评价 销量".into(),
                enabled: true,
                query_type: QueryType::Category,
                applicable_product_types: vec![],
            },
            QueryTemplate {
                name: "差评搜索".into(),
                template: "{core_keyword} 差评 质量 售后".into(),
                enabled: true,
                query_type: QueryType::Problem,
                applicable_product_types: vec![],
            },
        ],
        _ => vec![
            QueryTemplate {
                name: "General Search".into(),
                template: "{core_keyword}".into(),
                enabled: true,
                query_type: QueryType::Category,
                applicable_product_types: vec![],
            },
        ],
    }
}

/// Auto-adjust platform weights based on product type.
pub fn product_type_platform_weights(product_form: &str) -> Vec<(String, f64)> {
    let lower = product_form.to_lowercase();
    if lower.contains("saas") || lower.contains("b2b") {
        vec![
            ("G2 / Capterra".into(), 1.5), ("Trustpilot".into(), 1.2),
            ("Reddit".into(), 1.2), ("Quora".into(), 1.1),
            ("Google Search".into(), 1.0), ("LinkedIn".into(), 0.9),
        ]
    } else if lower.contains("mobile") || lower.contains("app") {
        vec![
            ("App Store".into(), 1.5), ("Google Play".into(), 1.5),
            ("Reddit".into(), 1.3), ("TikTok".into(), 1.1),
            ("X / Twitter".into(), 1.0),
        ]
    } else if lower.contains("extension") || lower.contains("plugin") || lower.contains("browser") {
        vec![
            ("Chrome Web Store".into(), 1.5), ("Google Search".into(), 1.3),
            ("Reddit".into(), 1.3), ("Product Hunt".into(), 1.0),
            ("AlternativeTo".into(), 0.9),
        ]
    } else if lower.contains("ai") || lower.contains("agent") {
        vec![
            ("Product Hunt".into(), 1.5), ("Reddit".into(), 1.3),
            ("X / Twitter".into(), 1.2), ("AlternativeTo".into(), 1.1),
            ("Google Trends".into(), 0.9),
        ]
    } else if lower.contains("ecommerce") || lower.contains("shop") || lower.contains("电商") {
        vec![
            ("Amazon".into(), 1.3), ("Taobao".into(), 1.2),
            ("JD.com".into(), 1.2), ("Reddit".into(), 1.1),
            ("Google Search".into(), 1.0),
        ]
    } else {
        vec![
            ("Google Search".into(), 1.2), ("Bing".into(), 1.1),
            ("Reddit".into(), 1.2), ("Quora".into(), 1.0),
            ("G2 / Capterra".into(), 1.0), ("Trustpilot".into(), 0.9),
        ]
    }
}

pub fn default_scoring_weights() -> HashMap<String, f64> {
    let mut m = HashMap::new();
    m.insert("time_window_week".into(), 1.5);
    m.insert("time_window_month".into(), 1.2);
    m.insert("time_window_quarter".into(), 1.0);
    m.insert("time_window_year".into(), 0.7);
    m.insert("time_window_older".into(), 0.4);
    m.insert("content_type_review".into(), 1.3);
    m.insert("content_type_forum".into(), 1.1);
    m.insert("content_type_social".into(), 0.9);
    m.insert("content_type_blog".into(), 0.7);
    m.insert("content_type_news".into(), 0.6);
    m
}
