import React, { useState } from "react";
import { ResearchProject, AppSettings, DimensionScore } from "../types";
import {
  BarChart3, BrainCircuit, Activity, ShieldAlert, Zap,
  HelpCircle, Sliders, RefreshCw, Loader2, Award, AlertTriangle,
  Plus, Search, UserPlus, Settings2
} from "lucide-react";

interface EvaluationViewProps {
  project: ResearchProject;
  settings: AppSettings;
  onUpdateProject: (updated: ResearchProject) => void;
  onReevaluate: (strategyMode?: string) => Promise<void>;
  isLoading: boolean;
  onNavigateToTab?: (tab: string) => void;
}

export default function EvaluationView({
  project,
  settings,
  onUpdateProject,
  onReevaluate,
  isLoading,
  onNavigateToTab,
}: EvaluationViewProps) {
  const [selectedDimName, setSelectedDimName] = useState<string>("需求强度");
  const cn = settings.language === "zh";

  const getSelectedDimTranslation = (name: string) => {
    if (cn) return name;
    const map: { [key: string]: string } = {
      "需求强度": "Demand Strength",
      "痛点强度": "Pain Severity",
      "市场拥挤度": "Market Congestion",
      "差异化空间": "Differentiation Space",
      "用户不满密度": "Dissatisfaction Density",
      "趋势方向": "Trend Direction",
      "商业化可行性": "Commercial Viability",
      "进入门槛": "Entry Barriers",
      "MVP 可验证性": "MVP Verifiability"
    };
    return map[name] || name;
  };

  const selectedDim = project.evaluation.dimensions.find(
    d => d.name === selectedDimName || d.name.includes(selectedDimName.slice(0, 2))
  ) || project.evaluation.dimensions[0];

  const handleSliderChange = (dimName: string, value: number) => {
    const updatedDims = project.evaluation.dimensions.map(dim => {
      // Allow partial match for safety
      if (dim.name === dimName || dim.name.includes(dimName.slice(0, 2))) {
        return {
          ...dim,
          score: value,
          reason: cn ? `${dim.reason} (用户手动调校数值)` : `${dim.reason} (User manually adjusted value on workstation)`
        };
      }
      return dim;
    });

    onUpdateProject({
      ...project,
      evaluation: {
        ...project.evaluation,
        dimensions: updatedDims
      }
    });
  };

  return (
    <div className="space-y-6 animate-fade-in p-1">
      {/* Upper overview stats */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {/* Recommendation card */}
        <div className="bg-white rounded-xl border border-gray-250 p-6 text-left shadow-sm relative overflow-hidden">
          <div className="absolute top-0 right-0 p-4 opacity-5 text-indigo-950">
            <Award size={100} />
          </div>
          <div className="space-y-2">
            <span className="text-[10px] font-mono font-bold uppercase text-gray-400 block tracking-tight">
              {cn ? "总研判结论建议" : "Verdict Consensus"}
            </span>
            <div className="text-xl font-bold text-gray-900 border-b border-gray-100 pb-2">
              {project.evaluation.overallRecommendation}
            </div>
            <p className="text-xs text-gray-500 leading-relaxed font-sans">
              {cn 
                ? "基于大模型引擎评估，融合全网抓取到的竞品不满密集度，以及您设置的加权分配对数据做出如上推荐路线判定。"
                : "Consensus generated by parsing actual G2 negative ratings averages and user voice friction vectors."}
            </p>
          </div>
        </div>

        {/* Confidence rating */}
        <div className="bg-white rounded-xl border border-gray-250 p-6 text-left shadow-sm relative">
          <div className="space-y-2">
            <span className="text-[10px] font-mono font-bold uppercase text-gray-400 block tracking-tight">
              {cn ? "模型置信度得分" : "Dossier Confidence Score"}
            </span>
            <div className="flex items-baseline gap-2">
              <span className="text-4xl font-sans font-bold text-indigo-600">
                {project.evaluation.confidenceScore}
              </span>
              <span className="text-sm font-sans font-medium text-gray-500">%</span>
            </div>
            {/* Progress bar */}
            <div className="w-full bg-gray-100 h-2 rounded-full overflow-hidden mt-2">
              <div 
                className="bg-indigo-600 h-full rounded-full transition-all duration-300" 
                style={{ width: `${project.evaluation.confidenceScore}%` }}
              />
            </div>
            <p className="text-[10px] text-gray-400 font-mono mt-1">
              {cn 
                ? `证据网络：${project.searchTasks.filter(t => t.status === "success").length}个渠道全绿成功，回收文献一致性显著。`
                : `Evidence trust: consistent matching signals recovered from active database crawlers.`}
            </p>
          </div>
        </div>

        {/* Sync panel weights */}
        <div className="bg-indigo-950 text-white rounded-xl border border-gray-800 p-6 text-left shadow-md flex flex-col justify-between">
          <div className="space-y-1">
            <h4 className="font-bold text-sm tracking-tight flex items-center gap-1.5 text-indigo-100">
              <BrainCircuit size={16} />
              {cn ? "动态证据链加权调校" : "Dynamic Calibrate Command"}
            </h4>
            <p className="text-[11px] text-gray-300 leading-relaxed">
              {cn 
                ? "当您改变左侧维度的滑块分值、或更改平台优先级，可点击此键：命令模型重新进行切入策略生成和验证路径生成。"
                : "Altering slider evaluation ranks? Tap the recalculate action. The server prompts the model to redesign strategic funnels."}
            </p>
          </div>

          <button
            onClick={onReevaluate}
            disabled={isLoading}
            className="w-full mt-4 bg-indigo-600 hover:bg-slate-100 hover:text-indigo-950 hover:border-slate-100 text-white border border-indigo-500 py-2 rounded-lg text-xs font-semibold flex items-center justify-center gap-1.5 transition cursor-pointer disabled:opacity-50"
          >
            {isLoading ? (
              <>
                <Loader2 size={12} className="animate-spin" />
                {cn ? "大模型深度校真中..." : "Re-bundling matrix data..."}
              </>
            ) : (
              <>
                <RefreshCw size={12} />
                {cn ? "重新计算并生成切入战略" : "Recalculate & Align Strategy"}
              </>
            )}
          </button>
        </div>
      </div>

      {/* Main layout Matrix sliders & justification detail */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Silders Matrix */}
        <div className="lg:col-span-2 bg-white rounded-xl border border-gray-250 p-6 text-left shadow-sm space-y-4">
          <div className="flex items-center justify-between pb-3 border-b border-gray-100">
            <h3 className="font-bold text-gray-900 text-sm flex items-center gap-2">
              <Sliders size={16} className="text-gray-600" />
              {cn ? "九维核心价值度量矩阵" : "9-Dimensional Value Ranks"}
            </h3>
            <span className="text-[10px] text-gray-400 font-mono font-medium">
              {cn ? "刻度：1 (极低) 至 10 (极高)" : "Range: 1 (min) to 10 (max)"}
            </span>
          </div>

          <div className="space-y-4">
            {project.evaluation.dimensions.map((dim) => {
              const isSelected = selectedDim?.name === dim.name || dim.name.includes(selectedDimName.slice(0, 2));
              return (
                <div 
                  key={dim.name}
                  onClick={() => setSelectedDimName(dim.name)}
                  className={`p-3 rounded-lg border transition duration-150 cursor-pointer ${
                    isSelected ? "border-indigo-200 bg-slate-50/50" : "border-gray-50 hover:bg-gray-50/30"
                  }`}
                >
                  <div className="flex items-center justify-between pointer-events-none pb-1.5">
                    <span className="text-xs font-bold text-gray-800 font-mono">
                      {getSelectedDimTranslation(dim.name)}
                    </span>
                    <span className="text-xs font-mono font-bold text-indigo-700 bg-indigo-50 px-2 py-0.5 rounded">
                      {dim.score} / 10
                    </span>
                  </div>

                  <div className="flex items-center gap-3">
                    <input
                      type="range"
                      min="1"
                      max="10"
                      value={dim.score}
                      onChange={(e) => handleSliderChange(dim.name, parseInt(e.target.value))}
                      className="w-full h-1.5 bg-gray-200 rounded-lg appearance-none cursor-pointer accent-indigo-600"
                    />
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Justification details cards */}
        {selectedDim && (
          <div className="space-y-4 text-left">
            <div className="bg-white rounded-xl border border-gray-250 p-6 shadow-sm space-y-4">
              <div className="space-y-1">
                <span className="inline-flex items-center gap-1.5 bg-indigo-50 text-indigo-800 text-[10px] font-mono font-bold px-2 py-0.5 rounded uppercase">
                  <Activity size={10} />
                  {cn ? "维度解释及依据" : "Audit Justification"}
                </span>
                <h3 className="font-bold text-gray-900 text-base">
                  {getSelectedDimTranslation(selectedDim.name)}
                </h3>
              </div>

              <p className="text-xs text-gray-600 leading-relaxed border-b border-gray-100 pb-3">
                {selectedDim.description}
              </p>

              <div className="space-y-1">
                <span className="text-[10px] font-mono font-bold uppercase text-gray-400 block tracking-tight">
                  {cn ? "文献事实提取说服力证据" : "Telemetry Supporting Evidence"}
                </span>
                <p className="text-xs text-gray-800 font-sans leading-relaxed italic bg-amber-50/40 p-3 rounded border border-amber-100 inline-block w-full">
                  "{selectedDim.reason}"
                </p>
              </div>
            </div>

            {/* Opportunities & Risks bullet Summary */}
            <div className="bg-slate-50 rounded-xl p-5 border border-gray-200 space-y-4">
              <div className="space-y-3 text-xs">
                <div className="space-y-1">
                  <span className="font-mono font-bold text-emerald-800 bg-emerald-50 px-2 py-0.5 rounded text-[10px] inline-flex items-center gap-1">
                    <Zap size={10} />
                    {cn ? "调研锁定的主要机会" : "Research Identified Opportunities"}
                  </span>
                  <div className="text-gray-700 font-sans pl-1 whitespace-pre-line leading-relaxed">
                    {project.evaluation.keyOpportunities}
                  </div>
                </div>

                <div className="space-y-1 border-t border-gray-200 mt-3 pt-3">
                  <span className="font-mono font-bold text-rose-800 bg-rose-50 px-2 py-0.5 rounded text-[10px] inline-flex items-center gap-1">
                    <ShieldAlert size={10} />
                    {cn ? "模型监测提示的核心阻碍" : "Telemetry Flagged Risks"}
                  </span>
                  <div className="text-gray-700 font-sans pl-1 whitespace-pre-line leading-relaxed">
                    {project.evaluation.keyRisks}
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>

      {/* P1-5: Corrective Actions Panel */}
      <div className="bg-white rounded-xl border border-gray-250 p-6 text-left shadow-sm">
        <div className="flex items-center gap-2 pb-3 border-b border-gray-100 mb-4">
          <Settings2 size={16} className="text-gray-600" />
          <h3 className="font-bold text-gray-900 text-sm">
            {cn ? "修正动作 / 补充调研" : "Corrective Actions"}
          </h3>
          <span className="text-[10px] text-gray-400 font-mono ml-auto">
            {cn ? "评估不满意？调整后重新计算" : "Not satisfied? Adjust and recalculate"}
          </span>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3">
          <button
            onClick={() => onNavigateToTab?.("platforms")}
            className="flex items-center gap-2 p-3 border border-[#E5E2DE] rounded-lg hover:border-black bg-white transition cursor-pointer text-left"
          >
            <Plus size={14} className="text-indigo-600" />
            <div>
              <div className="text-xs font-bold text-gray-900">{cn ? "追加平台" : "Add Platforms"}</div>
              <div className="text-[10px] text-gray-500">{cn ? "调整平台配置" : "Adjust platform configs"}</div>
            </div>
          </button>
          <button
            onClick={() => onNavigateToTab?.("modeling")}
            className="flex items-center gap-2 p-3 border border-[#E5E2DE] rounded-lg hover:border-black bg-white transition cursor-pointer text-left"
          >
            <Search size={14} className="text-indigo-600" />
            <div>
              <div className="text-xs font-bold text-gray-900">{cn ? "扩大查询" : "Expand Queries"}</div>
              <div className="text-[10px] text-gray-500">{cn ? "调整关键词和类别" : "Adjust keywords & categories"}</div>
            </div>
          </button>
          <button
            onClick={() => onNavigateToTab?.("competitors")}
            className="flex items-center gap-2 p-3 border border-[#E5E2DE] rounded-lg hover:border-black bg-white transition cursor-pointer text-left"
          >
            <UserPlus size={14} className="text-indigo-600" />
            <div>
              <div className="text-xs font-bold text-gray-900">{cn ? "补充竞品" : "Add Competitors"}</div>
              <div className="text-[10px] text-gray-500">{cn ? "手动添加遗漏竞品" : "Manually add missed competitors"}</div>
            </div>
          </button>
          <button
            onClick={onReevaluate}
            disabled={isLoading}
            className="flex items-center gap-2 p-3 border border-indigo-200 rounded-lg hover:border-indigo-600 bg-indigo-50/50 transition cursor-pointer text-left disabled:opacity-50"
          >
            {isLoading ? (
              <Loader2 size={14} className="animate-spin text-indigo-600" />
            ) : (
              <RefreshCw size={14} className="text-indigo-600" />
            )}
            <div>
              <div className="text-xs font-bold text-gray-900">{cn ? "重新计算" : "Recalculate"}</div>
              <div className="text-[10px] text-gray-500">{cn ? "含策略与验证计划" : "Strategy + validation plan"}</div>
            </div>
          </button>
        </div>
      </div>
    </div>
  );
}
